version: "3.9"
services:
  postgresql:
    container_name: postgresql
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kazuyo.rikudo@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgresql

  edinet_api:
    container_name: edinet_api
    build:
      context: ./edinet_api
      dockerfile: Dockerfile
    restart: always
    entrypoint: >
      uvicorn main:app --host 0.0.0.0  --reload  --port=8000
    expose:
      - 8000
      - 888
      - 8001
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:8001:8001
      - 127.0.0.1:8888:8888
    volumes:
      - ./edinet_api:/opt/app
      - ./edinet_api/root_jupyter:/root/.jupyter
    env_file:
      - ./edinet_api/edinet.env

  web:
    container_name: web
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./nextjs:/opt/app:cached
      - web_node_modules:/opt/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"

volumes:
  postgres_volume:
  volume_pgadmin:
  web_node_modules:
